language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install git+https://www.github.com/farizrahman4u/keras-contrib.git"
script:
  - "nosetests"